/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;

import javax.annotation.*;

import jhi.gatekeeper.server.database.tables.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnapprovedUsersRecord extends UpdatableRecordImpl<UnapprovedUsersRecord> implements Record14<Integer, String, String, String, String, Integer, String, String, String, Integer, Timestamp, Byte, Byte, String> {

    private static final long serialVersionUID = -1258095849;

    /**
     * Create a detached UnapprovedUsersRecord
     */
    public UnapprovedUsersRecord() {
        super(UnapprovedUsers.UNAPPROVED_USERS);
    }

    /**
     * Create a detached, initialised UnapprovedUsersRecord
     */
    public UnapprovedUsersRecord(Integer id, String userUsername, String userPassword, String userFullName, String userEmailAddress, Integer institutionId, String institutionName, String institutionAcronym, String institutionAddress, Integer databaseSystemId, Timestamp createdOn, Byte hasBeenRejected, Byte needsApproval, String activationKey) {
        super(UnapprovedUsers.UNAPPROVED_USERS);

        set(0, id);
        set(1, userUsername);
        set(2, userPassword);
        set(3, userFullName);
        set(4, userEmailAddress);
        set(5, institutionId);
        set(6, institutionName);
        set(7, institutionAcronym);
        set(8, institutionAddress);
        set(9, databaseSystemId);
        set(10, createdOn);
        set(11, hasBeenRejected);
        set(12, needsApproval);
        set(13, activationKey);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.user_username</code>.
     */
    public String getUserUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.user_username</code>.
     */
    public void setUserUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.user_password</code>.
     */
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.user_password</code>.
     */
    public void setUserPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.user_full_name</code>.
     */
    public String getUserFullName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.user_full_name</code>.
     */
    public void setUserFullName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.user_email_address</code>.
     */
    public String getUserEmailAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.user_email_address</code>.
     */
    public void setUserEmailAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.institution_id</code>.
     */
    public Integer getInstitutionId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.institution_id</code>.
     */
    public void setInstitutionId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.institution_name</code>.
     */
    public String getInstitutionName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.institution_name</code>.
     */
    public void setInstitutionName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.institution_acronym</code>.
     */
    public String getInstitutionAcronym() {
        return (String) get(7);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.institution_acronym</code>.
     */
    public void setInstitutionAcronym(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.institution_address</code>.
     */
    public String getInstitutionAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.institution_address</code>.
     */
    public void setInstitutionAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.database_system_id</code>.
     */
    public Integer getDatabaseSystemId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.database_system_id</code>.
     */
    public void setDatabaseSystemId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.has_been_rejected</code>.
     */
    public Byte getHasBeenRejected() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.has_been_rejected</code>.
     */
    public void setHasBeenRejected(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.needs_approval</code>.
     */
    public Byte getNeedsApproval() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.needs_approval</code>.
     */
    public void setNeedsApproval(Byte value) {
        set(12, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>germinate_gatekeeper.unapproved_users.activation_key</code>.
     */
    public String getActivationKey() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>germinate_gatekeeper.unapproved_users.activation_key</code>.
     */
    public void setActivationKey(String value) {
        set(13, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, Integer, String, String, String, Integer, Timestamp, Byte, Byte, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, Integer, String, String, String, Integer, Timestamp, Byte, Byte, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UnapprovedUsers.UNAPPROVED_USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UnapprovedUsers.UNAPPROVED_USERS.USER_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UnapprovedUsers.UNAPPROVED_USERS.USER_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UnapprovedUsers.UNAPPROVED_USERS.USER_FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UnapprovedUsers.UNAPPROVED_USERS.USER_EMAIL_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UnapprovedUsers.UNAPPROVED_USERS.INSTITUTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UnapprovedUsers.UNAPPROVED_USERS.INSTITUTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UnapprovedUsers.UNAPPROVED_USERS.INSTITUTION_ACRONYM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UnapprovedUsers.UNAPPROVED_USERS.INSTITUTION_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return UnapprovedUsers.UNAPPROVED_USERS.DATABASE_SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return UnapprovedUsers.UNAPPROVED_USERS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return UnapprovedUsers.UNAPPROVED_USERS.HAS_BEEN_REJECTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return UnapprovedUsers.UNAPPROVED_USERS.NEEDS_APPROVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return UnapprovedUsers.UNAPPROVED_USERS.ACTIVATION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getInstitutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getInstitutionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getInstitutionAcronym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getInstitutionAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getDatabaseSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getHasBeenRejected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component13() {
        return getNeedsApproval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getInstitutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInstitutionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getInstitutionAcronym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getInstitutionAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDatabaseSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getHasBeenRejected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getNeedsApproval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value2(String value) {
        setUserUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value4(String value) {
        setUserFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value5(String value) {
        setUserEmailAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value6(Integer value) {
        setInstitutionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value7(String value) {
        setInstitutionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value8(String value) {
        setInstitutionAcronym(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value9(String value) {
        setInstitutionAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value10(Integer value) {
        setDatabaseSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value12(Byte value) {
        setHasBeenRejected(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value13(Byte value) {
        setNeedsApproval(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord value14(String value) {
        setActivationKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnapprovedUsersRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, Integer value10, Timestamp value11, Byte value12, Byte value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }
}
