/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;

import javax.annotation.*;

import jhi.gatekeeper.server.database.*;
import jhi.gatekeeper.server.database.tables.records.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewUnapprovedUserDetails extends TableImpl<ViewUnapprovedUserDetailsRecord> {

    private static final long serialVersionUID = 1100010813;

    /**
     * The reference instance of <code>germinate_gatekeeper.view_unapproved_user_details</code>
     */
    public static final ViewUnapprovedUserDetails VIEW_UNAPPROVED_USER_DETAILS = new ViewUnapprovedUserDetails();
    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.has_been_rejected</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, Byte> HAS_BEEN_REJECTED = createField("has_been_rejected", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.id</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.username</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.full_name</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.email_address</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> EMAIL_ADDRESS = createField("email_address", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.created_on</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.institution_id</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, Integer> INSTITUTION_ID = createField("institution_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.name</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.acronym</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> ACRONYM = createField("acronym", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.address</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.database_system_name</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> DATABASE_SYSTEM_NAME = createField("database_system_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.database_server_name</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> DATABASE_SERVER_NAME = createField("database_server_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");
    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.needs_approval</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, Byte> NEEDS_APPROVAL = createField("needs_approval", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewUnapprovedUserDetailsRecord> getRecordType() {
        return ViewUnapprovedUserDetailsRecord.class;
    }

    /**
     * The column <code>germinate_gatekeeper.view_unapproved_user_details.activation_key</code>.
     */
    public final TableField<ViewUnapprovedUserDetailsRecord, String> ACTIVATION_KEY = createField("activation_key", org.jooq.impl.SQLDataType.VARCHAR(36), this, "");

    /**
     * Create a <code>germinate_gatekeeper.view_unapproved_user_details</code> table reference
     */
    public ViewUnapprovedUserDetails() {
        this(DSL.name("view_unapproved_user_details"), null);
    }

    /**
     * Create an aliased <code>germinate_gatekeeper.view_unapproved_user_details</code> table reference
     */
    public ViewUnapprovedUserDetails(String alias) {
        this(DSL.name(alias), VIEW_UNAPPROVED_USER_DETAILS);
    }

    /**
     * Create an aliased <code>germinate_gatekeeper.view_unapproved_user_details</code> table reference
     */
    public ViewUnapprovedUserDetails(Name alias) {
        this(alias, VIEW_UNAPPROVED_USER_DETAILS);
    }

    private ViewUnapprovedUserDetails(Name alias, Table<ViewUnapprovedUserDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewUnapprovedUserDetails(Name alias, Table<ViewUnapprovedUserDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    public <O extends Record> ViewUnapprovedUserDetails(Table<O> child, ForeignKey<O, ViewUnapprovedUserDetailsRecord> key) {
        super(child, key, VIEW_UNAPPROVED_USER_DETAILS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GerminateGatekeeper.GERMINATE_GATEKEEPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUnapprovedUserDetails as(String alias) {
        return new ViewUnapprovedUserDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUnapprovedUserDetails as(Name alias) {
        return new ViewUnapprovedUserDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewUnapprovedUserDetails rename(String name) {
        return new ViewUnapprovedUserDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewUnapprovedUserDetails rename(Name name) {
        return new ViewUnapprovedUserDetails(name, null);
    }
}
