/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables;


import jhi.gatekeeper.server.database.GatekeeperDb;
import jhi.gatekeeper.server.database.Keys;
import jhi.gatekeeper.server.database.tables.records.DatabaseSystemsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabaseSystems extends TableImpl<DatabaseSystemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gatekeeper_db.database_systems</code>
     */
    public static final DatabaseSystems DATABASE_SYSTEMS = new DatabaseSystems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatabaseSystemsRecord> getRecordType() {
        return DatabaseSystemsRecord.class;
    }

    /**
     * The column <code>gatekeeper_db.database_systems.id</code>.
     */
    public final TableField<DatabaseSystemsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gatekeeper_db.database_systems.system_name</code>.
     */
    public final TableField<DatabaseSystemsRecord, String> SYSTEM_NAME = createField(DSL.name("system_name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>gatekeeper_db.database_systems.server_name</code>.
     */
    public final TableField<DatabaseSystemsRecord, String> SERVER_NAME = createField(DSL.name("server_name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>gatekeeper_db.database_systems.description</code>.
     */
    public final TableField<DatabaseSystemsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    private DatabaseSystems(Name alias, Table<DatabaseSystemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatabaseSystems(Name alias, Table<DatabaseSystemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gatekeeper_db.database_systems</code> table
     * reference
     */
    public DatabaseSystems(String alias) {
        this(DSL.name(alias), DATABASE_SYSTEMS);
    }

    /**
     * Create an aliased <code>gatekeeper_db.database_systems</code> table
     * reference
     */
    public DatabaseSystems(Name alias) {
        this(alias, DATABASE_SYSTEMS);
    }

    /**
     * Create a <code>gatekeeper_db.database_systems</code> table reference
     */
    public DatabaseSystems() {
        this(DSL.name("database_systems"), null);
    }

    public <O extends Record> DatabaseSystems(Table<O> child, ForeignKey<O, DatabaseSystemsRecord> key) {
        super(child, key, DATABASE_SYSTEMS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GatekeeperDb.GATEKEEPER_DB;
    }

    @Override
    public Identity<DatabaseSystemsRecord, Integer> getIdentity() {
        return (Identity<DatabaseSystemsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatabaseSystemsRecord> getPrimaryKey() {
        return Keys.KEY_DATABASE_SYSTEMS_PRIMARY;
    }

    @Override
    public DatabaseSystems as(String alias) {
        return new DatabaseSystems(DSL.name(alias), this);
    }

    @Override
    public DatabaseSystems as(Name alias) {
        return new DatabaseSystems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatabaseSystems rename(String name) {
        return new DatabaseSystems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatabaseSystems rename(Name name) {
        return new DatabaseSystems(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
