/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jhi.gatekeeper.server.database.GatekeeperDb;
import jhi.gatekeeper.server.database.Indexes;
import jhi.gatekeeper.server.database.Keys;
import jhi.gatekeeper.server.database.tables.records.InstitutionsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Institutions extends TableImpl<InstitutionsRecord> {

    private static final long serialVersionUID = 807140672;

    /**
     * The reference instance of <code>gatekeeper_db.institutions</code>
     */
    public static final Institutions INSTITUTIONS = new Institutions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstitutionsRecord> getRecordType() {
        return InstitutionsRecord.class;
    }

    /**
     * The column <code>gatekeeper_db.institutions.id</code>.
     */
    public final TableField<InstitutionsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gatekeeper_db.institutions.name</code>.
     */
    public final TableField<InstitutionsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>gatekeeper_db.institutions.acronym</code>.
     */
    public final TableField<InstitutionsRecord, String> ACRONYM = createField("acronym", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gatekeeper_db.institutions.address</code>.
     */
    public final TableField<InstitutionsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>gatekeeper_db.institutions</code> table reference
     */
    public Institutions() {
        this(DSL.name("institutions"), null);
    }

    /**
     * Create an aliased <code>gatekeeper_db.institutions</code> table reference
     */
    public Institutions(String alias) {
        this(DSL.name(alias), INSTITUTIONS);
    }

    /**
     * Create an aliased <code>gatekeeper_db.institutions</code> table reference
     */
    public Institutions(Name alias) {
        this(alias, INSTITUTIONS);
    }

    private Institutions(Name alias, Table<InstitutionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Institutions(Name alias, Table<InstitutionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Institutions(Table<O> child, ForeignKey<O, InstitutionsRecord> key) {
        super(child, key, INSTITUTIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GatekeeperDb.GATEKEEPER_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INSTITUTIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<InstitutionsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INSTITUTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstitutionsRecord> getPrimaryKey() {
        return Keys.KEY_INSTITUTIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstitutionsRecord>> getKeys() {
        return Arrays.<UniqueKey<InstitutionsRecord>>asList(Keys.KEY_INSTITUTIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Institutions as(String alias) {
        return new Institutions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Institutions as(Name alias) {
        return new Institutions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Institutions rename(String name) {
        return new Institutions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Institutions rename(Name name) {
        return new Institutions(name, null);
    }
}
