/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.gatekeeper.server.database.GatekeeperDb;
import jhi.gatekeeper.server.database.tables.records.ViewAccessRequestUserDetailsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewAccessRequestUserDetails extends TableImpl<ViewAccessRequestUserDetailsRecord> {

    private static final long serialVersionUID = -711255278;

    /**
     * The reference instance of <code>gatekeeper_db.view_access_request_user_details</code>
     */
    public static final ViewAccessRequestUserDetails VIEW_ACCESS_REQUEST_USER_DETAILS = new ViewAccessRequestUserDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewAccessRequestUserDetailsRecord> getRecordType() {
        return ViewAccessRequestUserDetailsRecord.class;
    }

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.id</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.username</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.full_name</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.email_address</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> EMAIL_ADDRESS = createField("email_address", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.created_on</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.institution_id</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, Integer> INSTITUTION_ID = createField("institution_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.name</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.acronym</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> ACRONYM = createField("acronym", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.address</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.database_system_name</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> DATABASE_SYSTEM_NAME = createField("database_system_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.database_server_name</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> DATABASE_SERVER_NAME = createField("database_server_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.has_been_rejected</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, Byte> HAS_BEEN_REJECTED = createField("has_been_rejected", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.needs_approval</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, Byte> NEEDS_APPROVAL = createField("needs_approval", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gatekeeper_db.view_access_request_user_details.activation_key</code>.
     */
    public final TableField<ViewAccessRequestUserDetailsRecord, String> ACTIVATION_KEY = createField("activation_key", org.jooq.impl.SQLDataType.VARCHAR(36), this, "");

    /**
     * Create a <code>gatekeeper_db.view_access_request_user_details</code> table reference
     */
    public ViewAccessRequestUserDetails() {
        this(DSL.name("view_access_request_user_details"), null);
    }

    /**
     * Create an aliased <code>gatekeeper_db.view_access_request_user_details</code> table reference
     */
    public ViewAccessRequestUserDetails(String alias) {
        this(DSL.name(alias), VIEW_ACCESS_REQUEST_USER_DETAILS);
    }

    /**
     * Create an aliased <code>gatekeeper_db.view_access_request_user_details</code> table reference
     */
    public ViewAccessRequestUserDetails(Name alias) {
        this(alias, VIEW_ACCESS_REQUEST_USER_DETAILS);
    }

    private ViewAccessRequestUserDetails(Name alias, Table<ViewAccessRequestUserDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewAccessRequestUserDetails(Name alias, Table<ViewAccessRequestUserDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    public <O extends Record> ViewAccessRequestUserDetails(Table<O> child, ForeignKey<O, ViewAccessRequestUserDetailsRecord> key) {
        super(child, key, VIEW_ACCESS_REQUEST_USER_DETAILS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GatekeeperDb.GATEKEEPER_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewAccessRequestUserDetails as(String alias) {
        return new ViewAccessRequestUserDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewAccessRequestUserDetails as(Name alias) {
        return new ViewAccessRequestUserDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewAccessRequestUserDetails rename(String name) {
        return new ViewAccessRequestUserDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewAccessRequestUserDetails rename(Name name) {
        return new ViewAccessRequestUserDetails(name, null);
    }
}
