/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabaseSystems implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  systemName;
    private String  serverName;
    private String  description;

    public DatabaseSystems() {}

    public DatabaseSystems(DatabaseSystems value) {
        this.id = value.id;
        this.systemName = value.systemName;
        this.serverName = value.serverName;
        this.description = value.description;
    }

    public DatabaseSystems(
        Integer id,
        String  systemName,
        String  serverName,
        String  description
    ) {
        this.id = id;
        this.systemName = systemName;
        this.serverName = serverName;
        this.description = description;
    }

    /**
     * Getter for <code>gatekeeper_db.database_systems.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gatekeeper_db.database_systems.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gatekeeper_db.database_systems.system_name</code>.
     */
    public String getSystemName() {
        return this.systemName;
    }

    /**
     * Setter for <code>gatekeeper_db.database_systems.system_name</code>.
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    /**
     * Getter for <code>gatekeeper_db.database_systems.server_name</code>.
     */
    public String getServerName() {
        return this.serverName;
    }

    /**
     * Setter for <code>gatekeeper_db.database_systems.server_name</code>.
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * Getter for <code>gatekeeper_db.database_systems.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>gatekeeper_db.database_systems.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatabaseSystems (");

        sb.append(id);
        sb.append(", ").append(systemName);
        sb.append(", ").append(serverName);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
