/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DatabaseSystems implements Serializable
{

    private static final long serialVersionUID = -1254360302;

    private Integer id;
    private String  systemName;
    private String  serverName;
    private String  description;

    public DatabaseSystems()
    {
    }

    public DatabaseSystems(DatabaseSystems value)
    {
        this.id = value.id;
        this.systemName = value.systemName;
        this.serverName = value.serverName;
        this.description = value.description;
    }

    public DatabaseSystems(
        Integer id,
        String systemName,
        String serverName,
        String description
    )
    {
        this.id = id;
        this.systemName = systemName;
        this.serverName = serverName;
        this.description = description;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getSystemName()
    {
        return this.systemName;
    }

    public void setSystemName(String systemName)
    {
        this.systemName = systemName;
    }

    public String getServerName()
    {
        return this.serverName;
    }

    public void setServerName(String serverName)
    {
        this.serverName = serverName;
    }

    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("DatabaseSystems (");

        sb.append(id);
        sb.append(", ").append(systemName);
        sb.append(", ").append(serverName);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
