/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DatabaseVersion implements Serializable
{

    private static final long serialVersionUID = 201318655;

    private Integer   version;
    private Timestamp updatedOn;

    public DatabaseVersion()
    {
    }

    public DatabaseVersion(DatabaseVersion value)
    {
        this.version = value.version;
        this.updatedOn = value.updatedOn;
    }

    public DatabaseVersion(
        Integer version,
        Timestamp updatedOn
    )
    {
        this.version = version;
        this.updatedOn = updatedOn;
    }

    public Integer getVersion()
    {
        return this.version;
    }

    public void setVersion(Integer version)
    {
        this.version = version;
    }

    public Timestamp getUpdatedOn()
    {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn)
    {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("DatabaseVersion (");

        sb.append(version);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
