/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Institutions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private String  acronym;
    private String  address;

    public Institutions() {}

    public Institutions(Institutions value) {
        this.id = value.id;
        this.name = value.name;
        this.acronym = value.acronym;
        this.address = value.address;
    }

    public Institutions(
        Integer id,
        String  name,
        String  acronym,
        String  address
    ) {
        this.id = id;
        this.name = name;
        this.acronym = acronym;
        this.address = address;
    }

    /**
     * Getter for <code>gatekeeper_db.institutions.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gatekeeper_db.institutions.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gatekeeper_db.institutions.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>gatekeeper_db.institutions.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>gatekeeper_db.institutions.acronym</code>.
     */
    public String getAcronym() {
        return this.acronym;
    }

    /**
     * Setter for <code>gatekeeper_db.institutions.acronym</code>.
     */
    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    /**
     * Getter for <code>gatekeeper_db.institutions.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>gatekeeper_db.institutions.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Institutions (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(acronym);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }
}
