/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * Log table of password reset requests.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PasswordResetLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   userId;
    private Timestamp timestamp;
    private String    ipAddress;

    public PasswordResetLog() {}

    public PasswordResetLog(PasswordResetLog value) {
        this.userId = value.userId;
        this.timestamp = value.timestamp;
        this.ipAddress = value.ipAddress;
    }

    public PasswordResetLog(
        Integer   userId,
        Timestamp timestamp,
        String    ipAddress
    ) {
        this.userId = userId;
        this.timestamp = timestamp;
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for <code>gatekeeper_db.password_reset_log.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>gatekeeper_db.password_reset_log.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>gatekeeper_db.password_reset_log.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    /**
     * Setter for <code>gatekeeper_db.password_reset_log.timestamp</code>.
     */
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for <code>gatekeeper_db.password_reset_log.ip_address</code>.
     */
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Setter for <code>gatekeeper_db.password_reset_log.ip_address</code>.
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PasswordResetLog (");

        sb.append(userId);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(ipAddress);

        sb.append(")");
        return sb.toString();
    }
}
