/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Log table of password reset requests.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PasswordResetLog implements Serializable {

    private static final long serialVersionUID = 1627041594;

    private Integer   userId;
    private Timestamp timestamp;
    private String    ipAddress;

    public PasswordResetLog() {}

    public PasswordResetLog(PasswordResetLog value) {
        this.userId = value.userId;
        this.timestamp = value.timestamp;
        this.ipAddress = value.ipAddress;
    }

    public PasswordResetLog(
        Integer   userId,
        Timestamp timestamp,
        String    ipAddress
    ) {
        this.userId = userId;
        this.timestamp = timestamp;
        this.ipAddress = ipAddress;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PasswordResetLog (");

        sb.append(userId);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(ipAddress);

        sb.append(")");
        return sb.toString();
    }
}
