/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnapprovedUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    userUsername;
    private String    userPassword;
    private String    userFullName;
    private String    userEmailAddress;
    private Integer   institutionId;
    private String    institutionName;
    private String    institutionAcronym;
    private String    institutionAddress;
    private Integer   databaseSystemId;
    private Timestamp createdOn;
    private Byte      hasBeenRejected;
    private Byte      needsApproval;
    private String    activationKey;

    public UnapprovedUsers() {}

    public UnapprovedUsers(UnapprovedUsers value) {
        this.id = value.id;
        this.userUsername = value.userUsername;
        this.userPassword = value.userPassword;
        this.userFullName = value.userFullName;
        this.userEmailAddress = value.userEmailAddress;
        this.institutionId = value.institutionId;
        this.institutionName = value.institutionName;
        this.institutionAcronym = value.institutionAcronym;
        this.institutionAddress = value.institutionAddress;
        this.databaseSystemId = value.databaseSystemId;
        this.createdOn = value.createdOn;
        this.hasBeenRejected = value.hasBeenRejected;
        this.needsApproval = value.needsApproval;
        this.activationKey = value.activationKey;
    }

    public UnapprovedUsers(
        Integer   id,
        String    userUsername,
        String    userPassword,
        String    userFullName,
        String    userEmailAddress,
        Integer   institutionId,
        String    institutionName,
        String    institutionAcronym,
        String    institutionAddress,
        Integer   databaseSystemId,
        Timestamp createdOn,
        Byte      hasBeenRejected,
        Byte      needsApproval,
        String    activationKey
    ) {
        this.id = id;
        this.userUsername = userUsername;
        this.userPassword = userPassword;
        this.userFullName = userFullName;
        this.userEmailAddress = userEmailAddress;
        this.institutionId = institutionId;
        this.institutionName = institutionName;
        this.institutionAcronym = institutionAcronym;
        this.institutionAddress = institutionAddress;
        this.databaseSystemId = databaseSystemId;
        this.createdOn = createdOn;
        this.hasBeenRejected = hasBeenRejected;
        this.needsApproval = needsApproval;
        this.activationKey = activationKey;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.user_username</code>.
     */
    public String getUserUsername() {
        return this.userUsername;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.user_username</code>.
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.user_password</code>.
     */
    public String getUserPassword() {
        return this.userPassword;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.user_password</code>.
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.user_full_name</code>.
     */
    public String getUserFullName() {
        return this.userFullName;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.user_full_name</code>.
     */
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.unapproved_users.user_email_address</code>.
     */
    public String getUserEmailAddress() {
        return this.userEmailAddress;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.unapproved_users.user_email_address</code>.
     */
    public void setUserEmailAddress(String userEmailAddress) {
        this.userEmailAddress = userEmailAddress;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.institution_id</code>.
     */
    public Integer getInstitutionId() {
        return this.institutionId;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.institution_id</code>.
     */
    public void setInstitutionId(Integer institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.institution_name</code>.
     */
    public String getInstitutionName() {
        return this.institutionName;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.institution_name</code>.
     */
    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.unapproved_users.institution_acronym</code>.
     */
    public String getInstitutionAcronym() {
        return this.institutionAcronym;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.unapproved_users.institution_acronym</code>.
     */
    public void setInstitutionAcronym(String institutionAcronym) {
        this.institutionAcronym = institutionAcronym;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.unapproved_users.institution_address</code>.
     */
    public String getInstitutionAddress() {
        return this.institutionAddress;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.unapproved_users.institution_address</code>.
     */
    public void setInstitutionAddress(String institutionAddress) {
        this.institutionAddress = institutionAddress;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.unapproved_users.database_system_id</code>.
     */
    public Integer getDatabaseSystemId() {
        return this.databaseSystemId;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.unapproved_users.database_system_id</code>.
     */
    public void setDatabaseSystemId(Integer databaseSystemId) {
        this.databaseSystemId = databaseSystemId;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.has_been_rejected</code>.
     */
    public Byte getHasBeenRejected() {
        return this.hasBeenRejected;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.has_been_rejected</code>.
     */
    public void setHasBeenRejected(Byte hasBeenRejected) {
        this.hasBeenRejected = hasBeenRejected;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.needs_approval</code>.
     */
    public Byte getNeedsApproval() {
        return this.needsApproval;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.needs_approval</code>.
     */
    public void setNeedsApproval(Byte needsApproval) {
        this.needsApproval = needsApproval;
    }

    /**
     * Getter for <code>gatekeeper_db.unapproved_users.activation_key</code>.
     */
    public String getActivationKey() {
        return this.activationKey;
    }

    /**
     * Setter for <code>gatekeeper_db.unapproved_users.activation_key</code>.
     */
    public void setActivationKey(String activationKey) {
        this.activationKey = activationKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UnapprovedUsers (");

        sb.append(id);
        sb.append(", ").append(userUsername);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userFullName);
        sb.append(", ").append(userEmailAddress);
        sb.append(", ").append(institutionId);
        sb.append(", ").append(institutionName);
        sb.append(", ").append(institutionAcronym);
        sb.append(", ").append(institutionAddress);
        sb.append(", ").append(databaseSystemId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(hasBeenRejected);
        sb.append(", ").append(needsApproval);
        sb.append(", ").append(activationKey);

        sb.append(")");
        return sb.toString();
    }
}
