/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHasAccessToDatabases implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private Integer databaseId;
    private Integer userTypeId;
    private Byte    primaryContact;

    public UserHasAccessToDatabases() {}

    public UserHasAccessToDatabases(UserHasAccessToDatabases value) {
        this.userId = value.userId;
        this.databaseId = value.databaseId;
        this.userTypeId = value.userTypeId;
        this.primaryContact = value.primaryContact;
    }

    public UserHasAccessToDatabases(
        Integer userId,
        Integer databaseId,
        Integer userTypeId,
        Byte    primaryContact
    ) {
        this.userId = userId;
        this.databaseId = databaseId;
        this.userTypeId = userTypeId;
        this.primaryContact = primaryContact;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.user_has_access_to_databases.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.user_has_access_to_databases.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.user_has_access_to_databases.database_id</code>.
     */
    public Integer getDatabaseId() {
        return this.databaseId;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.user_has_access_to_databases.database_id</code>.
     */
    public void setDatabaseId(Integer databaseId) {
        this.databaseId = databaseId;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.user_has_access_to_databases.user_type_id</code>.
     */
    public Integer getUserTypeId() {
        return this.userTypeId;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.user_has_access_to_databases.user_type_id</code>.
     */
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    /**
     * Getter for
     * <code>gatekeeper_db.user_has_access_to_databases.primary_contact</code>.
     */
    public Byte getPrimaryContact() {
        return this.primaryContact;
    }

    /**
     * Setter for
     * <code>gatekeeper_db.user_has_access_to_databases.primary_contact</code>.
     */
    public void setPrimaryContact(Byte primaryContact) {
        this.primaryContact = primaryContact;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserHasAccessToDatabases (");

        sb.append(userId);
        sb.append(", ").append(databaseId);
        sb.append(", ").append(userTypeId);
        sb.append(", ").append(primaryContact);

        sb.append(")");
        return sb.toString();
    }
}
