/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCounts implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long users;
    private Long requests;
    private Long databases;

    public ViewCounts() {}

    public ViewCounts(ViewCounts value) {
        this.users = value.users;
        this.requests = value.requests;
        this.databases = value.databases;
    }

    public ViewCounts(
        Long users,
        Long requests,
        Long databases
    ) {
        this.users = users;
        this.requests = requests;
        this.databases = databases;
    }

    /**
     * Getter for <code>gatekeeper_db.view_counts.users</code>.
     */
    public Long getUsers() {
        return this.users;
    }

    /**
     * Setter for <code>gatekeeper_db.view_counts.users</code>.
     */
    public void setUsers(Long users) {
        this.users = users;
    }

    /**
     * Getter for <code>gatekeeper_db.view_counts.requests</code>.
     */
    public Long getRequests() {
        return this.requests;
    }

    /**
     * Setter for <code>gatekeeper_db.view_counts.requests</code>.
     */
    public void setRequests(Long requests) {
        this.requests = requests;
    }

    /**
     * Getter for <code>gatekeeper_db.view_counts.databases</code>.
     */
    public Long getDatabases() {
        return this.databases;
    }

    /**
     * Setter for <code>gatekeeper_db.view_counts.databases</code>.
     */
    public void setDatabases(Long databases) {
        this.databases = databases;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewCounts (");

        sb.append(users);
        sb.append(", ").append(requests);
        sb.append(", ").append(databases);

        sb.append(")");
        return sb.toString();
    }
}
