/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ViewCounts implements Serializable
{

    private static final long serialVersionUID = 779724777;

    private Long users;
    private Long requests;
    private Long databases;

    public ViewCounts()
    {
    }

    public ViewCounts(ViewCounts value)
    {
        this.users = value.users;
        this.requests = value.requests;
        this.databases = value.databases;
    }

    public ViewCounts(
        Long users,
        Long requests,
        Long databases
    )
    {
        this.users = users;
        this.requests = requests;
        this.databases = databases;
    }

    public Long getUsers()
    {
        return this.users;
    }

    public void setUsers(Long users)
    {
        this.users = users;
    }

    public Long getRequests()
    {
        return this.requests;
    }

    public void setRequests(Long requests)
    {
        this.requests = requests;
    }

    public Long getDatabases()
    {
        return this.databases;
    }

    public void setDatabases(Long databases)
    {
        this.databases = databases;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ViewCounts (");

        sb.append(users);
        sb.append(", ").append(requests);
        sb.append(", ").append(databases);

        sb.append(")");
        return sb.toString();
    }
}
