/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.*;

import javax.annotation.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Institutions implements Serializable {

    private static final long serialVersionUID = -1316177758;

    private Integer id;
    private String  name;
    private String  acronym;
    private String  address;

    public Institutions() {}

    public Institutions(Institutions value) {
        this.id = value.id;
        this.name = value.name;
        this.acronym = value.acronym;
        this.address = value.address;
    }

    public Institutions(
        Integer id,
        String  name,
        String  acronym,
        String  address
    ) {
        this.id = id;
        this.name = name;
        this.acronym = acronym;
        this.address = address;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAcronym() {
        return this.acronym;
    }

    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Institutions (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(acronym);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }
}
