/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.pojos;


import java.io.*;
import java.sql.*;

import javax.annotation.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewAccessRequestUserDetails implements Serializable {

    private static final long serialVersionUID = -28908581;

    private Integer   id;
    private String    username;
    private String    fullName;
    private String    emailAddress;
    private Timestamp createdOn;
    private Integer   institutionId;
    private String    name;
    private String    acronym;
    private String    address;
    private String    databaseSystemName;
    private String    databaseServerName;
    private Byte      hasBeenRejected;
    private Byte      needsApproval;
    private String    activationKey;

    public ViewAccessRequestUserDetails() {}

    public ViewAccessRequestUserDetails(ViewAccessRequestUserDetails value) {
        this.id = value.id;
        this.username = value.username;
        this.fullName = value.fullName;
        this.emailAddress = value.emailAddress;
        this.createdOn = value.createdOn;
        this.institutionId = value.institutionId;
        this.name = value.name;
        this.acronym = value.acronym;
        this.address = value.address;
        this.databaseSystemName = value.databaseSystemName;
        this.databaseServerName = value.databaseServerName;
        this.hasBeenRejected = value.hasBeenRejected;
        this.needsApproval = value.needsApproval;
        this.activationKey = value.activationKey;
    }

    public ViewAccessRequestUserDetails(
        Integer   id,
        String    username,
        String    fullName,
        String    emailAddress,
        Timestamp createdOn,
        Integer   institutionId,
        String    name,
        String    acronym,
        String    address,
        String    databaseSystemName,
        String    databaseServerName,
        Byte      hasBeenRejected,
        Byte      needsApproval,
        String    activationKey
    ) {
        this.id = id;
        this.username = username;
        this.fullName = fullName;
        this.emailAddress = emailAddress;
        this.createdOn = createdOn;
        this.institutionId = institutionId;
        this.name = name;
        this.acronym = acronym;
        this.address = address;
        this.databaseSystemName = databaseSystemName;
        this.databaseServerName = databaseServerName;
        this.hasBeenRejected = hasBeenRejected;
        this.needsApproval = needsApproval;
        this.activationKey = activationKey;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Integer getInstitutionId() {
        return this.institutionId;
    }

    public void setInstitutionId(Integer institutionId) {
        this.institutionId = institutionId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAcronym() {
        return this.acronym;
    }

    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDatabaseSystemName() {
        return this.databaseSystemName;
    }

    public void setDatabaseSystemName(String databaseSystemName) {
        this.databaseSystemName = databaseSystemName;
    }

    public String getDatabaseServerName() {
        return this.databaseServerName;
    }

    public void setDatabaseServerName(String databaseServerName) {
        this.databaseServerName = databaseServerName;
    }

    public Byte getHasBeenRejected() {
        return this.hasBeenRejected;
    }

    public void setHasBeenRejected(Byte hasBeenRejected) {
        this.hasBeenRejected = hasBeenRejected;
    }

    public Byte getNeedsApproval() {
        return this.needsApproval;
    }

    public void setNeedsApproval(Byte needsApproval) {
        this.needsApproval = needsApproval;
    }

    public String getActivationKey() {
        return this.activationKey;
    }

    public void setActivationKey(String activationKey) {
        this.activationKey = activationKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewAccessRequestUserDetails (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(fullName);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(institutionId);
        sb.append(", ").append(name);
        sb.append(", ").append(acronym);
        sb.append(", ").append(address);
        sb.append(", ").append(databaseSystemName);
        sb.append(", ").append(databaseServerName);
        sb.append(", ").append(hasBeenRejected);
        sb.append(", ").append(needsApproval);
        sb.append(", ").append(activationKey);

        sb.append(")");
        return sb.toString();
    }
}
