/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.records;


import jhi.gatekeeper.server.database.tables.UserTypes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTypesRecord extends UpdatableRecordImpl<UserTypesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gatekeeper_db.user_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gatekeeper_db.user_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gatekeeper_db.user_types.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gatekeeper_db.user_types.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserTypes.USER_TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return UserTypes.USER_TYPES.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public UserTypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserTypesRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserTypesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTypesRecord
     */
    public UserTypesRecord() {
        super(UserTypes.USER_TYPES);
    }

    /**
     * Create a detached, initialised UserTypesRecord
     */
    public UserTypesRecord(Integer id, String description) {
        super(UserTypes.USER_TYPES);

        setId(id);
        setDescription(description);
    }

    /**
     * Create a detached, initialised UserTypesRecord
     */
    public UserTypesRecord(jhi.gatekeeper.server.database.tables.pojos.UserTypes value) {
        super(UserTypes.USER_TYPES);

        if (value != null) {
            setId(value.getId());
            setDescription(value.getDescription());
        }
    }
}
