/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.TableRecordImpl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.gatekeeper.server.database.tables.ViewUserDetails;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ViewUserDetailsRecord extends TableRecordImpl<ViewUserDetailsRecord> implements Record9<Integer, String, String, String, Timestamp, Byte, String, String, String>
{

    private static final long serialVersionUID = 40935023;

    /**
     * Create a detached ViewUserDetailsRecord
     */
    public ViewUserDetailsRecord()
    {
        super(ViewUserDetails.VIEW_USER_DETAILS);
    }

    /**
     * Create a detached, initialised ViewUserDetailsRecord
     */
    public ViewUserDetailsRecord(Integer id, String username, String fullName, String emailAddress, Timestamp createdOn, Byte gatekeeperAccess, String name, String acronym, String address)
    {
        super(ViewUserDetails.VIEW_USER_DETAILS);

        set(0, id);
        set(1, username);
        set(2, fullName);
        set(3, emailAddress);
        set(4, createdOn);
        set(5, gatekeeperAccess);
        set(6, name);
        set(7, acronym);
        set(8, address);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.id</code>.
     */
    public Integer getId()
    {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.id</code>.
     */
    public void setId(Integer value)
    {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.username</code>.
     */
    public String getUsername()
    {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.username</code>.
     */
    public void setUsername(String value)
    {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.full_name</code>.
     */
    public String getFullName()
    {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.full_name</code>.
     */
    public void setFullName(String value)
    {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.email_address</code>.
     */
    public String getEmailAddress()
    {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.email_address</code>.
     */
    public void setEmailAddress(String value)
    {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.created_on</code>.
     */
    public Timestamp getCreatedOn()
    {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.created_on</code>.
     */
    public void setCreatedOn(Timestamp value)
    {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.gatekeeper_access</code>.
     */
    public Byte getGatekeeperAccess()
    {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.gatekeeper_access</code>.
     */
    public void setGatekeeperAccess(Byte value)
    {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.name</code>.
     */
    public String getName()
    {
        return (String) get(6);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.name</code>.
     */
    public void setName(String value)
    {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Byte, String, String, String> fieldsRow()
    {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Timestamp, Byte, String, String, String> valuesRow()
    {
        return (Row9) super.valuesRow();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.EMAIL_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.GATEKEEPER_ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.ACRONYM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9()
    {
        return ViewUserDetails.VIEW_USER_DETAILS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1()
    {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2()
    {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3()
    {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4()
    {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5()
    {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6()
    {
        return getGatekeeperAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7()
    {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8()
    {
        return getAcronym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9()
    {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1()
    {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2()
    {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3()
    {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4()
    {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5()
    {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6()
    {
        return getGatekeeperAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7()
    {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8()
    {
        return getAcronym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9()
    {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value1(Integer value)
    {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value2(String value)
    {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value3(String value)
    {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value4(String value)
    {
        setEmailAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value5(Timestamp value)
    {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value6(Byte value)
    {
        setGatekeeperAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value7(String value)
    {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value8(String value)
    {
        setAcronym(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord value9(String value)
    {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserDetailsRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Byte value6, String value7, String value8, String value9)
    {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.acronym</code>.
     */
    public String getAcronym()
    {
        return (String) get(7);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.acronym</code>.
     */
    public void setAcronym(String value)
    {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>germinate_gatekeeper.view_user_details.address</code>.
     */
    public String getAddress()
    {
        return (String) get(8);
    }

    /**
     * Setter for <code>germinate_gatekeeper.view_user_details.address</code>.
     */
    public void setAddress(String value)
    {
        set(8, value);
    }
}
