/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database.tables.records;


import javax.annotation.Generated;

import jhi.gatekeeper.server.database.tables.ViewUserPermissions;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewUserPermissionsRecord extends TableRecordImpl<ViewUserPermissionsRecord> implements Record7<Integer, String, Integer, String, String, Integer, String> {

    private static final long serialVersionUID = 2123252450;

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.database_id</code>.
     */
    public void setDatabaseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.database_id</code>.
     */
    public Integer getDatabaseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.system_name</code>.
     */
    public void setSystemName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.system_name</code>.
     */
    public String getSystemName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.server_name</code>.
     */
    public void setServerName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.server_name</code>.
     */
    public String getServerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.user_type_id</code>.
     */
    public void setUserTypeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.user_type_id</code>.
     */
    public Integer getUserTypeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gatekeeper_db.view_user_permissions.user_type</code>.
     */
    public void setUserType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gatekeeper_db.view_user_permissions.user_type</code>.
     */
    public String getUserType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, String, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, String, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.DATABASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.SYSTEM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.SERVER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.USER_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewUserPermissions.VIEW_USER_PERMISSIONS.USER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDatabaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSystemName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getServerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDatabaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSystemName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getServerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value3(Integer value) {
        setDatabaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value4(String value) {
        setSystemName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value5(String value) {
        setServerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value6(Integer value) {
        setUserTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord value7(String value) {
        setUserType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewUserPermissionsRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewUserPermissionsRecord
     */
    public ViewUserPermissionsRecord() {
        super(ViewUserPermissions.VIEW_USER_PERMISSIONS);
    }

    /**
     * Create a detached, initialised ViewUserPermissionsRecord
     */
    public ViewUserPermissionsRecord(Integer userId, String username, Integer databaseId, String systemName, String serverName, Integer userTypeId, String userType) {
        super(ViewUserPermissions.VIEW_USER_PERMISSIONS);

        set(0, userId);
        set(1, username);
        set(2, databaseId);
        set(3, systemName);
        set(4, serverName);
        set(5, userTypeId);
        set(6, userType);
    }
}
