/*
 * This file is generated by jOOQ.
 */
package jhi.gatekeeper.server.database;


import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

import java.util.*;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl
{

    /**
     * The reference instance of <code></code>
     */
    public static final  DefaultCatalog      DEFAULT_CATALOG      = new DefaultCatalog();
    private static final long                serialVersionUID     = 1285458689;
    /**
     * The schema <code>germinate_gatekeeper</code>.
     */
    public final         GerminateGatekeeper GERMINATE_GATEKEEPER = jhi.gatekeeper.server.database.GerminateGatekeeper.GERMINATE_GATEKEEPER;

    /**
     * No further instances allowed
     */
    private DefaultCatalog()
    {
        super("");
    }

    @Override
    public final List<Schema> getSchemas()
    {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0()
    {
        return Arrays.<Schema>asList(
            GerminateGatekeeper.GERMINATE_GATEKEEPER);
    }
}
